#### 3. Create a null vector of size 10 (★☆☆)

In [1]:
import numpy as np
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [2]:
Z = np.zeros(10)
Z[4] = 1
Z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [6]:
Z = np.arange(10,50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [3]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [4]:
Z = np.array([1,2,0,0,4,0])
Z.nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [9]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## 12. Create a 3x3x3 array with random values (★☆☆)

In [5]:
np.random.random((3, 3, 3))

array([[[ 0.68774033,  0.88524347,  0.52693362],
        [ 0.94104599,  0.33465467,  0.26530454],
        [ 0.26685034,  0.38382869,  0.37126553]],

       [[ 0.43869671,  0.47071311,  0.68504113],
        [ 0.98096456,  0.55116129,  0.15149589],
        [ 0.33271879,  0.86134241,  0.37817667]],

       [[ 0.26385595,  0.20412551,  0.19946957],
        [ 0.11254649,  0.44348412,  0.73483048],
        [ 0.78627411,  0.757541  ,  0.78391136]]])

In [8]:
np.random.normal(0,1,(3,3,3))

array([[[-0.76147551, -0.99001487,  0.75270739],
        [-0.33948995, -0.54095027,  0.79372061],
        [-0.17836805,  0.8560222 , -0.03755091]],

       [[-1.24851876, -1.01812389,  2.1723165 ],
        [-0.99547037,  1.56424532,  0.99352138],
        [-0.10768666,  0.66010073,  0.11868248]],

       [[-0.42042721,  0.47339424, -1.02168816],
        [-1.89369409, -0.16281528, -0.59443206],
        [-1.75339989, -0.97218971, -0.46259017]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
Z = np.random.random((10, 10))
print(Z.min(), Z.max())

0.0299016487533 0.975668742339


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
np.random.random(30).mean()

0.53708820249005429

## 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
# 1: the second, -1: the last second
Z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

## 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [14]:
Z = np.ones((5,5))
np.pad(Z, pad_width=1, mode='constant', constant_values=0)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

## 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [17]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [15]:
Z = np.zeros((8,8), dtype = int)
Z[::2, 1::2] = 1
# ::2 - 从头开始，每两个取一个
# m::n - 从index为m开始，每n个取一个
Z[1::2, ::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [16]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
Z = np.random.random((5,5))
Zmin, Zmax = Z.min(), Z.max()
Z = (Z - Zmin) / (Zmax - Zmin)
Z

array([[ 0.        ,  0.86470449,  0.30839062,  0.921607  ,  0.38721819],
       [ 0.3504224 ,  1.        ,  0.50879927,  0.27136602,  0.63652176],
       [ 0.46071339,  0.37230705,  0.45041756,  0.40394523,  0.55489078],
       [ 0.75002818,  0.60870291,  0.10737616,  0.46107075,  0.1939704 ],
       [ 0.54209936,  0.23675294,  0.5963441 ,  0.09259374,  0.7861665 ]])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
np.dot(np.random.random((5,3)), np.random.random((3,2)))

array([[ 1.43778174,  1.13415978],
       [ 0.40028414,  0.30765417],
       [ 0.77552539,  0.21117286],
       [ 0.75179885,  0.61580877],
       [ 0.91372368,  0.8644388 ]])

## 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
Z = np.arange(20)
Z[(Z >= 3) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
Z1 = np.arange(10)
Z2 = np.arange(3,15)
np.intersect1d(Z1, Z2)

array([3, 4, 5, 6, 7, 8, 9])

## 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [39]:
print(np.datetime64('today'),
      np.datetime64('today') + np.timedelta64(-1)) # yesterday

2018-01-11 2018-01-10


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [48]:
Z = np.random.normal(3,8,20)
print(Z)
[np.floor(i) if i >=0 else np.ceil(i) for i in Z]

[ -1.10916287   2.96563307  -1.06513134   4.79116788   0.36142411
 -17.83250809   1.54897285 -17.65046964  12.87184414   7.12620571
  18.16823283   8.92605327  -3.23069087  21.33806261  18.55094572
  12.43091436   1.63868225  -8.72029441  -6.86435423  -7.57698865]


[-1.0,
 2.0,
 -1.0,
 4.0,
 0.0,
 -17.0,
 1.0,
 -17.0,
 12.0,
 7.0,
 18.0,
 8.0,
 -3.0,
 21.0,
 18.0,
 12.0,
 1.0,
 -8.0,
 -6.0,
 -7.0]

## 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [54]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

## 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [59]:
def generate():
    for x in range(10):
        yield x

np.fromiter(generate(), dtype = int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [62]:
np.linspace(0,1,12)[1:-1]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [63]:
np.sort(np.random.random(10))

array([ 0.25959426,  0.30300337,  0.34312975,  0.54741004,  0.62195464,
        0.65980672,  0.72412054,  0.75039635,  0.8193942 ,  0.9785446 ])

## 42. Consider two random array A and B, check if they are equal (★★☆)

In [71]:
A = np.random.randint(0,10,6)
B = np.random.randint(0,10,6)
C = A.reshape(2,3)
print(A, B, C)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
print(np.allclose(A,B))
# print(np.allclose(A,C))

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
print(np.array_equal(A,B))
print(np.array_equal(A,C))

[3 0 6 2 5 5] [1 2 6 2 6 8] [[3 0 6]
 [2 5 5]]
False
False
False


## 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [73]:
Z = np.random.random(10)
print(Z, Z.max())
Z[Z.argmax()] = 0
print(Z, Z.max())

[ 0.28397297  0.39000719  0.13702733  0.11191661  0.63967032  0.64804361
  0.19058824  0.22098897  0.01547113  0.72856985] 0.728569846013
[ 0.28397297  0.39000719  0.13702733  0.11191661  0.63967032  0.64804361
  0.19058824  0.22098897  0.01547113  0.        ] 0.648043605068


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [83]:
Z = np.random.rand(5,10)
print(Z)
print(Z-Z.mean(axis=1).reshape(-1,1))

[[ 0.64485804  0.92942511  0.65830822  0.1057907   0.47513445  0.08507068
   0.5528152   0.10658361  0.28346391  0.36250539]
 [ 0.66511588  0.55918265  0.43904982  0.85701799  0.41406088  0.37240949
   0.40293934  0.90835572  0.12710403  0.25901039]
 [ 0.64453696  0.33980272  0.26201109  0.13647239  0.07353915  0.59460534
   0.51139865  0.77556638  0.96784606  0.70034746]
 [ 0.35801046  0.27595128  0.82297048  0.83387287  0.88197738  0.65430847
   0.20812709  0.13134847  0.24182093  0.52639331]
 [ 0.35638235  0.69428573  0.78453128  0.53632076  0.12395457  0.89759984
   0.2037854   0.59190564  0.29780044  0.77547738]]
[[ 0.22446251  0.50902958  0.23791269 -0.31460483  0.05473892 -0.33532485
   0.13241967 -0.31381192 -0.13693162 -0.05789014]
 [ 0.16469126  0.05875803 -0.0613748   0.35659337 -0.08636374 -0.12801513
  -0.09748527  0.40793111 -0.37332059 -0.24141423]
 [ 0.14392434 -0.1608099  -0.23860153 -0.36414023 -0.42707347  0.09399273
   0.01078603  0.27495376  0.46723344  0.19973484]

## 59. How to sort an array by the nth column? (★★☆)

In [84]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])
print(Z[Z[:,1].argsort()])
print(Z[Z[:,2].argsort()])

[[4 3 6]
 [4 5 3]
 [6 6 7]]
[[4 3 6]
 [4 5 3]
 [6 6 7]]
[[4 3 6]
 [4 5 3]
 [6 6 7]]
[[4 5 3]
 [4 3 6]
 [6 6 7]]


#### 69. How to get the diagonal of a dot product? (★★★)

In [89]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([ 1.19071478,  0.58746949,  1.2025207 ,  1.2207074 ,  1.42159604])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [100]:
Y = np.arange(1,6)
Z=np.zeros(17)
Z[::4] = Y
Z

array([ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
        0.,  0.,  0.,  5.])

## 72. How to swap two rows of an array? (★★★)

In [107]:
A = np.arange(25).reshape(5,5)
A[[1,4]] = A[[4,1]]
A

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9]])

## 83. How to find the most frequent value in an array?

In [109]:
Z = np.random.randint(0,10,20)
print(Z, np.bincount(Z).argmax())

[9 9 5 3 1 5 7 5 0 0 6 9 0 9 8 3 0 6 2 9] 9


## 89. How to get the n largest values of an array (★★★)

In [118]:
Z = np.arange(100)
np.random.shuffle(Z)
Y = Z
print(Y)

n = 2
Y[Y.argsort()[-n:]]

[16 82 44 54 80 83 57 25 84 76  9 70 41 37 39 71  1 67 47 38 52 91 98  5 85
 12 31  4 42  7 11 63 56 34 29 48 24 59 90 49 88 97 78 87 81 53 95 20 61 36
 74  3 15 50 65 19 27 68 55  2 62 43 18 99 21 22 60 40 28 35  0 86 89 10 96
 64 73 46 30 77 66 75 51 17 33 79 94 13 14 32 26  8 72 69 45  6 23 93 58 92]


array([98, 99])